### ISSUE TITLE
카카오아레나 전화번호 인증오류

### ISSUE THREAD

**Issue by junwoopark92** [kakao-arena/brunch-article-recommendation#1]
카카오아레나 사이트에 대한 문제를 올려서 죄송합니다.

전화번호 인증이 되지않으면 아레나에 FAQ도 올릴수 없어 이곳에 올립니다.

아레나에서 팀생성이나 댓글을 달려면 전화번호 인증을 해야하는데 마이페이지에서 전화번호 인증을 하려고하면 이미 인증된 번호라고 나옵니다.

확인부탁드립니다.

**Comment by arena-admin** [comment]
@junwoopark92 
사이트 리뉴얼하면서 기존 가입자들의 인증 과정에 문제가 생겼습니다.
현재는 해소되었으며 다시 한번 확인 부탁드립니다.
불편을 드려서 죄송합니다.

**Comment by junwoopark92** [comment]
시크릿창에서 다시 해본결과도 여전히 동일합니다 ㅠㅠ

[image: image.png]
[image: image.png]
ᐧ

2019년 6월 23일 (일) 오전 11:16, arena-admin <notifications@github.com>님이 작성:

**Comment by arena-admin** [comment]
@junwoopark92 인증이 된 것으로 확인이 되는데, 여전히 안 되는 상황일까요?

**Comment by junwoopark92** [comment]
아네 현재는 정상적으로 팀등록까지 진행하였습니다. 감사합니다~
ᐧ

2019년 6월 23일 (일) 오후 12:01, arena-admin <notifications@github.com>님이 작성:
